### ISSUE TITLE
TurbSim manual

### ISSUE THREAD

**Issue by falascao** [OpenFAST/r-test#119]
Hi,
recently i had see a manual where, step by step, i can set all the parameter of the 90m_12mps_twr.INP for TurbSim like type of turbolence,  WindProfileType, Power law exponent and Surface roughness length for offshore.
Now, i can't find this manual.
Can you help me?
Best regards,

Andrea

**Comment by jjonkman** [comment]
Dear @falascao,

The TurbSim User's Guide is available here: https://openfast.readthedocs.io/en/main/_downloads/cb14d3e2d3533d76e405d730fea19846/TurbSim_v2.00.pdf.

Best regards,

**Comment by falascao** [comment]
Thank you @jjonkman.
Best regards,
