### ISSUE TITLE
`Tailfin_FreeYaw1DOF_PolarBased` airfoil has linear cl curve

### ISSUE THREAD

**Issue by bjonkman** [OpenFAST/r-test#125]
When running the OpenFAST `Tailfin_FreeYaw1DOF_PolarBased` case, this warning appears:

> FAST_InitializeAll:AD_Init:Init_AFIparams:AFI_Init:ReadAFfile:Airfoil data should go from -180
> degrees to 180 degrees and the coefficients at the ends should be the same.

It looks like the airfoil file in that case has a linear `cl` curve instead of something periodic. See
https://github.com/OpenFAST/r-test/blob/main/glue-codes/openfast/Tailfin_FreeYaw1DOF_PolarBased/Polar_2PiAlpha.dat

![image](https://github.com/OpenFAST/r-test/assets/6108781/58fa89cf-7b12-4834-934c-a45821e88b7f)

**Comment by andrew-platt** [comment]
@abhineet-gupta, can you look at this?

**Comment by andrew-platt** [comment]
Replaced this airfoil with the NACA-0018 with PR #137 (thanks @abhineet-gupta)

This test case is a toy problem, so any sensible looking airfoil table should work.
