### ISSUE TITLE
OpenFAST v4.0 deprecates AD 14

### ISSUE THREAD

**Issue by rafmudaf** [OpenFAST/r-test#43]
The release of OpenFAST v3.0.0 will deprecate AeroDyn 14, and the module will be removed in a subsequent release. The regression tests using AeroDyn 14 will need to be modified to use AeroDyn 15.

An existing pull request starts the process: https://github.com/OpenFAST/r-test/pull/18.

**Comment by andrew-platt** [comment]
The release of v4.0.0 will deprecate AD14.  There are now enough projects that need AD14 removed that I'll get to it in the next few weeks.

**Comment by andrew-platt** [comment]
This has been completed.
