### ISSUE TITLE
Is there a detail description of the wind turbine models?

### ISSUE THREAD

**Issue by tatesnow** [OpenFAST/r-test#46]
I currently only have an introduction of 5-MW Reference Wind Turbine for Offshore, the other model such as 5MW_OC4Semi_WSt_WavesWN, where can I find a description of other wind turbines?

**Comment by jjonkman** [comment]
Dear @tatesnow,

The OC4-DeepCwind semisubmersible that can be used to support the NREL 5-MW baseline wind turbine in a floating configuration is documented in the following NREL technical report: https://www.nrel.gov/docs/fy14osti/60601.pdf.

Best regards,

**Comment by tatesnow** [comment]
Dear @jjonkman,
Thank you very much!
