### ISSUE TITLE
aerodyne.dat file is missing

### ISSUE THREAD

**Issue by jyotrimaya1993** [OpenFAST/r-test#57]
primary aerodyne.dat file is missing

although it has NRELOffshrBsline5MW_AeroDyn_Equil_noTwr.dat but after run the .fst file,it shows aerodyn.dat file is missing

**Comment by jjonkman** [comment]
Dear @jyotrimaya1993

I'm sorry, but I'm not sure I understand your question.  Please clarify.

Best regards,
