### ISSUE TITLE
Error in r-test/glue-codes/openfast/5MW_Land_ModeShapes

### ISSUE THREAD

**Issue by Prithvi2029** [OpenFAST/r-test#58]
Hello, 
I was trying to run this case using openfast_x64.exe and 5MW_Land_ModeShapes.fst as the input file but it's showed multiple errors in NRELOffshrBsline5MW_Onshore_AeroDyn15.dat file one of them was misaligned AFAeroMod, but after I corrected that.... compAA  was missing and further I corrected that keyword, soon many other errors popped up. Do I need to modify these files before running example test cases or they should be running as it is?

Thank you for your time and guidance. 
![Screenshot 2022-05-27 153009](https://user-images.githubusercontent.com/64565000/170785284-52058bb3-435b-4e15-bbce-ce545be0c6c5.png)

**Comment by jjonkman** [comment]
Dear @Prithvi2029,

I'm not sure why, but it doesn't appear that this r-test input file is up-to-date with OpenFAST v3.1.  However, you should be able to use the AeroDyn v15 input from the following r-test, which is up-to-date, as long as you set `AFAeroMod` = 1 and `FrozenWake` = True: https://github.com/OpenFAST/r-test/blob/main/glue-codes/openfast/5MW_Land_DLL_WTurb/NRELOffshrBsline5MW_Onshore_AeroDyn15.dat.

Best regards,

**Comment by Prithvi2029** [comment]
Hello @jjonkman , 
I did try that before and the new error which refers to 5MW Baseline model comes up.(As shown in attached screenshot). Could you refer me to a test case model which has wake modelling visualisation for a variable wind speed(doesnt matter if single turbine or multiple ? I seem to have issues in some test cases in the glue codes. 
 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/64565000/170788526-5067f06e-8ecf-4699-afe0-e6ed6aa7d67f.png">

**Comment by Prithvi2029** [comment]
Also, I have made the changes to the file as you suggested, Please review the pull request. 
Link to request - https://github.com/OpenFAST/r-test/pull/59

**Comment by jjonkman** [comment]
Regarding your new error, it appears that the InflowWind input file you are using is also out of date relative to OpenFAST v3.1.  An InflowWind input file is not included in the 5MW_Land_ModeShapes test, but you can find a properly formatted InflowWind input file here: https://github.com/OpenFAST/r-test/blob/main/glue-codes/openfast/5MW_Baseline/NRELOffshrBsline5MW_InflowWind_12mps.dat.

Regarding PR #59, you'll also need to add `CompAA` and `AA_InputFile` to the AeroDyn v15 input file for compatibility with the newest version of AeroDyn.

I'm not sure I understand your question regarding wake visualization.

Best regards,

**Comment by Prithvi2029** [comment]
Hello @jjonkman , 
Thank you for your suggestions. I have added those 2 lines as we discussed. But it's now throwing an error with missing 'VFlowAng' in file - 5MW_Baseline/NRELOffshrBsline5MW_InflowWind_Steady13mps.dat. (the last screenshot is attached)

By wake visualization, I meant that , if you can share with me the test case which shows wake effects in wind turbines such as shown in the image below. I am trying to apply some algorithms related to the wake model and visualize as the wind speed and direction change. Thereby use yaw control.  
![image](https://user-images.githubusercontent.com/64565000/170792639-71fc9e4e-ea4f-47f5-a2d6-c5a9328326f5.png)


Also, I have added the Discon.dll file with the mentioned commit, Please review - https://github.com/OpenFAST/r-test/pull/60

![image](https://user-images.githubusercontent.com/64565000/170792248-992d7bb6-66f5-4a93-9f0c-afeb84c68b74.png)

**Comment by jjonkman** [comment]
I responded regarding your InflowWind input file in my prior post.

We purposely don't distribute precompiled DISCON binary files for Windows in the r-test, which is otherwise generally applicable for any operating system.  Instead, these are provided separately here: https://github.com/OpenFAST/openfast/releases/download/v3.1.0/DISCON.DLLS.zip.  Please close PR #60.

Wake effects are computed within FAST.Farm, not standalone OpenFAST.  The r-test for FAST.Farm is available here: https://github.com/OpenFAST/r-test/tree/main/glue-codes/fast-farm.

Best regards,

**Comment by Prithvi2029** [comment]
After running LEFInflow which is from r-test of Fast farm, its missing the DISCON_WT1.dll file(screenshot 1). Do I have to edit the dll file to same name as missing file from the zip file from the above link you shared ? and even after editing the dll file name , FAST.farm isnt working. (screenshot 2 after I addded the DISCON.dll file from zip folder and changed the name to DISCON_WT1.dll)

<img width="773" alt="image" src="https://user-images.githubusercontent.com/64565000/170795396-305c8cea-7526-4562-85ab-720e44cb6336.png">


<img width="723" alt="image" src="https://user-images.githubusercontent.com/64565000/170795483-8e3bb250-dcac-4411-91f9-f1b6f43df45c.png">

**Comment by jjonkman** [comment]
Yes, that is correct.  The original _DISCON.dll_ for the NREL 5-MW baseline wind turbine must be renamed to _DISCON_WT1.dll_ for this test (no other change needs to be made, just the renaming).

Please note, however, that it appears that you are running standalone OpenFAST rather than FAST.Farm.  To run FAST.Farm, you must use a compiled binary executable of FAST.Farm and the FAST.Farm input file (_LESinflow.fstf_ for the LESinflow test).

**Comment by Prithvi2029** [comment]
Thank you for your patience and guidance, I was able to run the LES Inflow model. I appreaciate your inputs !
