### ISSUE TITLE
FAST: How can I get the force and moments in an exact location of the tower? 

### ISSUE THREAD

**Issue by Zakarneh0** [OpenFAST/r-test#92]
I'm trying to get the forces and the moments in the middle of the wind turbine tower, any advice on how to change the location of results from the hub to the desired point?

**Comment by jjonkman** [comment]
Dear @Zakarneh0,

Presumably you are running OpenFAST with the tower modeled in ElastoDyn?  If so, you can output the reaction forces in the middle of the tower by placing a structural analysis node there and outputting the loads via the tower node gage outputs, e.g., output channel `TwHt1MLyt` is the fore-aft bending moment at output gage 1.

Best regards,
